import { MenuItem } from '@/types/database';

export const MENU_ITEMS: MenuItem[] = [
    // --- ENTRADAS SENSORIALES ---
    {
        id: '1',
        name: 'Gold Wagyu Tartare',
        description: 'Caviar Osetra, yema curada en soja, lámina de oro 24k comestible.',
        price: 32.00,
        category: 'Entradas Sensoriales',
        type: 'STARTER',
        origin: 'Kagoshima, JP',
        image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=2070', // RESTORED original
    },
    {
        id: '2',
        name: 'Burrata Molecular',
        description: 'Espuma de tomate orgánico, tierra de aceituna negra, humo de romero en mesa.',
        price: 24.00,
        category: 'Entradas Sensoriales',
        type: 'STARTER',
        origin: 'Puglia, IT',
        image_url: 'https://images.unsplash.com/photo-1594910609689-d13de98d925e?auto=format&fit=crop&q=80&w=2070', // NEW VALID URL (Burrata/Salad)
    },
    {
        id: '3',
        name: 'Tuétano a la Brasa',
        description: 'Canoas de hueso asado, tostadas de masa madre, gremolata cítrica y sal maldón.',
        price: 20.00,
        category: 'Entradas Sensoriales',
        type: 'STARTER',
        origin: 'Nacional AAAA',
        image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=2069',
    },
    {
        id: '101',
        name: 'Carpaccio de Cocodrilo',
        description: 'Finas láminas marinadas en cítricos amazónicos, pimienta rosa y aceite de trufa.',
        price: 28.00,
        category: 'Entradas Sensoriales',
        type: 'STARTER',
        origin: 'Exotic Farm',
        image_url: 'https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '102',
        name: 'Ceviche de Chicharrón',
        description: 'Panceta crocante, leche de tigre ahumada, maiz cancha y batata dulce.',
        price: 22.00,
        category: 'Entradas Sensoriales',
        type: 'STARTER',
        origin: 'Fusión',
        image_url: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&q=80&w=2070',
    },

    // --- CORTES PREMIUM (INTERNACIONALES) ---
    {
        id: '4',
        name: 'Tomahawk "Prime" (1.2kg)',
        description: 'El rey de los cortes. Madurado 45 días en cámara de sal del Himalaya.',
        price: 140.00,
        category: 'Cortes Premium',
        type: 'MEAT',
        origin: 'Angus Prime, USA',
        image_url: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '5',
        name: 'Wagyu A5 Kagoshima (200g)',
        description: 'Marmoleo BMS 11-12. Servido con piedra caliente (Ishiyaki) para cocción al gusto.',
        price: 180.00,
        category: 'Cortes Premium',
        type: 'MEAT',
        origin: 'Kagoshima, JP',
        image_url: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '6',
        name: 'Ribeye Angus Gold (400g)',
        description: 'Ojo de bife con inyección de mantequilla de trufa negra.',
        price: 75.00,
        category: 'Cortes Premium',
        type: 'MEAT',
        origin: 'Angus Certified',
        image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '103',
        name: 'Porterhouse Dry Aged (900g)',
        description: 'Lo mejor de dos mundos: Filet Mignon y New York Strip. Maduración 60 días.',
        price: 110.00,
        category: 'Cortes Premium',
        type: 'MEAT',
        origin: 'USDA Prime',
        image_url: 'https://images.unsplash.com/photo-1504973960431-1c467e159aa4?auto=format&fit=crop&q=80&w=2070',
    },

    // --- CORTES NACIONALES (VENEZUELA) ---
    {
        id: '201',
        name: 'Solomo de Cuerito Santa Bárbara',
        description: 'Corte clásico zuliano, grasa externa crocante, sabor intenso de pastura.',
        price: 35.00,
        category: 'Cortes Nacionales',
        type: 'MEAT',
        origin: 'Zulia, VZLA',
        image_url: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?auto=format&fit=crop&q=80&w=2070', // NEW VALID URL
    },
    {
        id: '202',
        name: 'Punta Trasera Carora (800g)',
        description: 'La reina de la parrilla venezolana. Ganado caroreño de libre pastoreo.',
        price: 45.00,
        category: 'Cortes Nacionales',
        type: 'MEAT',
        origin: 'Lara, VZLA',
        image_url: 'https://images.unsplash.com/photo-1551028150-64b9f398f678?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '203',
        name: 'Lomito Viche (300g)',
        description: 'La pieza más tierna, envuelta en tocineta artesanal ahumada.',
        price: 38.00,
        category: 'Cortes Nacionales',
        type: 'MEAT',
        origin: 'Llanos, VZLA',
        image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=2070', // NEW VALID URL
    },

    // --- COCTELERÍA DE AUTOR ---
    {
        id: '7',
        name: 'The Ledger',
        description: 'Bourbon lavado en grasa de Wagyu (Fat-washed), maple ahumado, bitter de cacao.',
        price: 22.00,
        category: 'Coctelería de Autor',
        type: 'DRINK',
        origin: 'Signature',
        image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '8',
        name: 'Crypto Mule',
        description: 'Vodka premium, cordial de jengibre y cúrcuma, polvo de oro, top de soda.',
        price: 18.00,
        category: 'Coctelería de Autor',
        type: 'DRINK',
        origin: 'Signature',
        image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '301',
        name: 'NFT Martini',
        description: 'Gin Tanqueray Ten, Vermouth seco infusionado con algas, aceituna esférica.',
        price: 20.00,
        category: 'Coctelería de Autor',
        type: 'DRINK',
        origin: 'Signature',
        image_url: 'https://images.unsplash.com/photo-1575023782549-62ca0d244b39?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '302',
        name: 'Metaverse Mojito',
        description: 'Ron Diplomático Planas, hierbabuena nitrógenada, espuma de coco.',
        price: 16.00,
        category: 'Coctelería de Autor',
        type: 'DRINK',
        origin: 'Signature',
        image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=2070',
    },

    // --- COCTELERÍA CLÁSICA ---
    {
        id: '401',
        name: 'Smoked Old Fashioned',
        description: 'Bourbon, azúcar mascabado, angostura, ahumado en campana de roble.',
        price: 16.00,
        category: 'Coctelería Clásica',
        type: 'DRINK',
        origin: 'Classic',
        image_url: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&q=80&w=2069',
    },
    {
        id: '402',
        name: 'Negroni Sbagliato',
        description: 'Campari, Vermouth Rosso, Prosecco. "Un error perfecto".',
        price: 15.00,
        category: 'Coctelería Clásica',
        type: 'DRINK',
        origin: 'Classic',
        image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=2070',
    },
    {
        id: '403',
        name: 'Margarita Patron',
        description: 'Tequila Patron Silver, Cointreau, lima fresca, borde de sal negra.',
        price: 18.00,
        category: 'Coctelería Clásica',
        type: 'DRINK',
        origin: 'Classic',
        image_url: 'https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?auto=format&fit=crop&q=80&w=2070', // UPDATED: Classic Lime Margarita
    },
];
